# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#aboutsite"
  weight = 10

[[main]]
  name = "Research"
  url = "research/"
  weight = 20

[[main]]
  name = "Teaching"
  url = "teaching/"
  weight = 30

[[main]]
  name = "People"
  url = "people/"
  weight = 40

#[[main]]
#  name = "Masters"
#  parent = "research"
#  url = "masters/"
#  weight = 32

#[[main]]
#  name = "CV"
#  parent = "research"
#  url = "cv/CV_trivikverma.pdf"
#  weight = 34

#[[main]]
#  name = "Publications"
#  parent = "research"
#  url = "publications/"
#  weight = 31

#[[main]]
#  name = "Writing"
#  parent = "research"
#  url = "writing/"
#  weight = 33

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 40

[[main]]
  name = "News"
  url = "news/"
  weight = 50

#[[main]]
#  name = "Blog"
#  url = "blog/"
#  weight = 60

[[main]]
  name = "Opportunities"
  url = "opportunities/"
  weight = 60

[[main]]
  name = "Philosophy"
  url = "welcome/"
  weight = 70

[[main]]
  name = "Publications"
  url = "publications/"
  weight = 80

#[[main]]
#  name = "MSc Projects"
#  post = ""
#  url = "mscprojects/"
#  url = "courses/epa1316-2020/"
#  weight = 90
