# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#aboutsite"
  weight = 10

[[main]]
  name = "People"
  url = "people/"
  weight = 20

[[main]]
  name = "Research"
  identifier = "research"
  weight = 30

[[main]]
  name = "Masters"
  parent = "research"
  url = "masters/"
  weight = 32

[[main]]
  name = "CV"
  parent = "research"
  url = "cv/CV_trivikverma.pdf"
  weight = 34

[[main]]
  name = "Publications"
  parent = "research"
  url = "publication/"
  weight = 31

[[main]]
  name = "Writing"
  parent = "research"
  url = "writing/"
  weight = 33

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 40

[[main]]
  name = "News"
  url = "news/"
  weight = 50

[[main]]
  name = "Blog"
  url = "blog/"
  weight = 60

[[main]]
  name = "Openings"
  url = "openings/"
  weight = 70

[[main]]
  name = "Onboarding"
  url = "onboarding/"
  weight = 80

[[main]]
  name = "MSc Projects"
  post = ""
  url = "mscprojects/"
#  url = "courses/epa1316-2020/"
  weight = 90

[[main]]
  name = "<i class=\"fab fa-twitter\" style=\"color: #55acee; font-size: 1rem; line-height: 1.25\"></i>"
  post = ""
  url = "https://twitter.com/TrivikV"
  weight = 100
